version: 2

models:
  - name: silver_cores
    description: "SpaceX rocket cores (reusable boosters) with transformations and data quality improvements"
    columns:
      - name: id
        description: "Unique identifier for the core"
        tests:
          - not_null
      - name: status
        description: "Current status of the core (active, inactive, lost, etc.) in lowercase"
        tests:
          - not_null
      - name: serial
        description: "Serial number of the core"
      - name: reuse_count
        description: "Number of times this core has been reused"
        tests:
          - not_null
      - name: launches
        description: "JSON array of launch IDs where this core was used"
      - name: last_update_timestamp
        description: "Last update timestamp for this core converted to timestamp type"
      - name: valid_from
        description: "Timestamp when this record version became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this record version became invalid (null if current)"
      - name: is_current_record
        description: "Flag indicating if this is the current version of the record"
        tests:
          - not_null
      - name: source_load_id
        description: "Original dlt load identifier"
        tests:
          - not_null
      - name: silver_load_timestamp
        description: "Timestamp when this record was processed in silver layer"
        tests:
          - not_null

  - name: silver_launchpads
    description: "SpaceX launchpad facilities - silver layer with transformations and data quality improvements"
    columns:
      - name: id
        description: "Unique identifier for the launchpad"
        tests:
          - not_null
          - unique
      - name: name
        description: "Name of the launchpad"
        tests:
          - not_null
      - name: full_name
        description: "Full official name of the launchpad"
        tests:
          - not_null
      - name: locality
        description: "Local area where the launchpad is located"
      - name: region
        description: "Region where the launchpad is located"
      - name: latitude
        description: "Latitude coordinate of the launchpad"
      - name: longitude
        description: "Longitude coordinate of the launchpad"
      - name: launch_attempts
        description: "Total number of launch attempts from this pad"
        tests:
          - not_null
      - name: launch_successes
        description: "Total number of successful launches from this pad"
        tests:
          - not_null

      - name: launches
        description: "JSON array of launch IDs from this pad"
      - name: rockets
        description: "JSON array of rocket IDs that have used this pad"
      - name: status
        description: "Current operational status of the launchpad (lowercase)"
        tests:
          - not_null

      - name: details
        description: "Additional details about the launchpad"
      - name: timezone
        description: "Timezone of the launchpad location"

      - name: valid_from
        description: "Timestamp when this record version became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this record version became invalid (null if current)"
      - name: is_current_record
        description: "Flag indicating if this is the current version of the record"
        tests:
          - not_null
      - name: source_load_id
        description: "Original dlt load identifier"
        tests:
          - not_null
      - name: silver_load_timestamp
        description: "Timestamp when this record was processed in silver layer"
        tests:
          - not_null

  - name: silver_rockets
    description: "SpaceX rocket specifications with transformations and data quality improvements"
    columns:
      - name: id
        description: "Unique identifier for the rocket"
        tests:
          - not_null
      - name: name
        description: "Name of the rocket"
        tests:
          - not_null
      - name: description
        description: "Description of the rocket"
      - name: company
        description: "Company that built the rocket"
        tests:
          - not_null
      - name: type
        description: "Type of rocket"
      - name: active
        description: "Whether the rocket is currently active"
        tests:
          - not_null
      - name: stages
        description: "Number of stages in the rocket"
        tests:
          - not_null
      - name: boosters
        description: "Number of boosters"
        tests:
          - not_null
      - name: cost_per_launch
        description: "Cost per launch in USD"
      - name: success_rate_pct
        description: "Success rate percentage"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
      - name: country
        description: "Country of origin"
      - name: first_flight_date
        description: "Date of first flight, converted to date type"
      - name: valid_from
        description: "Timestamp when this record version became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this record version became invalid (null if current)"
      - name: is_current_record
        description: "Flag indicating if this is the current version of the record"
        tests:
          - not_null
      - name: source_load_id
        description: "Original dlt load identifier"
        tests:
          - not_null
      - name: silver_load_timestamp
        description: "Timestamp when this record was processed in silver layer"
        tests:
          - not_null

  - name: silver_ships
    description: "SpaceX ships used for recovery operations with transformations and data quality improvements"
    columns:
      - name: id
        description: "Unique identifier for the ship"
        tests:
          - not_null
      - name: name
        description: "Name of the ship"
        tests:
          - not_null
      - name: type
        description: "Type of ship (recovery, support, etc.) in lowercase"
        tests:
          - not_null
      - name: active
        description: "Whether the ship is currently active"
        tests:
          - not_null
      - name: mass_kg
        description: "Mass of the ship in kilograms"
      - name: year_built
        description: "Year the ship was built"
      - name: home_port
        description: "Home port of the ship"
      - name: model
        description: "Model of the ship"
      - name: launches
        description: "JSON array of launch IDs where this ship was involved"
      - name: valid_from
        description: "Timestamp when this record version became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this record version became invalid (null if current)"
      - name: is_current_record
        description: "Flag indicating if this is the current version of the record"
        tests:
          - not_null
      - name: source_load_id
        description: "Original dlt load identifier"
        tests:
          - not_null
      - name: silver_load_timestamp
        description: "Timestamp when this record was processed in silver layer"
        tests:
          - not_null
