[destination.snowflake.credentials]
database = "<configure me>" # fill this in!
password = "<configure me>" # fill this in!
username = "<configure me>" # fill this in!
host = "<configure me>" # fill this in!
warehouse = "<configure me>" # fill this in!
role = "<configure me>" # fill this in!
